language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

  jdk:
  - oraclejdk8
    
  before_script:
    - cd Android
    
  script:
    - gradle assemble
