language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

jdk:
- oraclejdk8
env:
  global:
  - USER="GhostBusters-APM"
  - EMAIL="GhostBusters-APM@github.com"
  - REPO="GhostHouseBuilds"
  - FILES="./build/apk/*"
  - GH_REPO="github.com/${USER}/${REPO}.git"

before_script:
  
  - wget http://services.gradle.org/distributions/gradle-4.4-bin.zip
  - unzip -qq gradle-4.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v
  - cd Android
  - yes | sdkmanager "platforms;android-26"
  
script:
  - gradle assemble

after_success:
  - tree -d 
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git rm ./*
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1
